#ifndef VOLBXPROPERTIES_H
#define VOLBXPROPERTIES_H

#define VER_FILEDESCRIPTION_STR "Volbx"
#define VER_INTERNALNAME_STR "Volbx"
#define VER_ORIGINALFILENAME_STR "Volbx.exe"
#define VER_PRODUCTNAME_STR "Volbx"

#endif  // VOLBXPROPERTIES_H
