#pragma once

#define VER_FILEVERSION 1, 0, 0, 0
#define VER_FILEVERSION_STR "1.0.0.0"

#define VER_PRODUCTVERSION 0, 2, 0, 0
#define VER_PRODUCTVERSION_STR "2.00"

#define VER_COMPANYNAME_STR "No Name"
#define VER_LEGALCOPYRIGHT_STR "Copyright 2014-2020"
#define VER_LEGALTRADEMARKS1_STR ""
#define VER_LEGALTRADEMARKS2_STR VER_LEGALTRADEMARKS1_STR

#define VER_COMPANYDOMAIN_STR ""
