#ifndef COMMONPROPERTIES_H
#define COMMONPROPERTIES_H

#define VER_FILEVERSION             1,0,0,0
#define VER_FILEVERSION_STR         "1.0.0.0\0"

#define VER_PRODUCTVERSION          0,1,1,0
#define VER_PRODUCTVERSION_STR      "1.10\0"

#define VER_COMPANYNAME_STR         "QuackTech"
#define VER_LEGALCOPYRIGHT_STR      "Copyright 2014"
#define VER_LEGALTRADEMARKS1_STR    ""
#define VER_LEGALTRADEMARKS2_STR    VER_LEGALTRADEMARKS1_STR

#define VER_COMPANYDOMAIN_STR       ""

#endif // COMMONPROPERTIES_H
